### ISSUE TITLE
Add a licence info

### ISSUE THREAD

**Issue by iamsjn** [topnotch48/ng-bullet-workspace#10]
Hi @topnotch48,
In this repo there are no licence info has been provided. Could you please add a licence info for this repo?

**Comment by topnotch48** [comment]
Hi @iamsjn, this repo is not being maintained really. Basically it was abandoned in favor of https://github.com/ngneat/spectator, which i would recommend to use instead. That repo has everything you need, including LICENCE file.

**Comment by iamsjn** [comment]
Thank you! I'll have a look onto it.
