### ISSUE TITLE
ng-bullet does not seem to consider providers

### ISSUE THREAD

**Issue by mickaeltr** [topnotch48/ng-bullet-workspace#3]
Hello,

In my project we are unit testing components by mocking services (using jest / jest-preset-angular / ts-jest).

```
const getReferenceData: GetReferenceDataService = new GetReferenceDataService(null);
mocked(getReferenceData).perform.mockReturnValue({…});

TestBed.configureTestingModule({
    declarations: […],
    imports: […],
    schemas: [CUSTOM_ELEMENTS_SCHEMA],
    providers: [{provide: GetReferenceDataService, useValue: getReferenceData}]
});
```

That works fine with the traditional way of writing TestBed tests… however I didn't manage to use ng-bullet (the `getReferenceData.perform` returns `undefined` instead of the mocked value).

Thanks

**Comment by chriszichrisz** [comment]
Try to use SinonJS to mock your services. https://sinonjs.org/

Worked for me also with ng-bullet

**Comment by pgrzywaczcic** [comment]
> Try to use SinonJS to mock your services. https://sinonjs.org/
> 
> Worked for me also with ng-bullet

Not really helpful.

What I've noticed is that providers with "useValue" (or maybe ALL providers, did not check yet) do not get reset between createTestingModule() calls. This means that on all subsequent tests reuse at least some of the old providers.

This probably isn't a problem for most, however it breaks test isolation and causes funny errors when providers have some state.

**Comment by christophercr** [comment]
I have exactly the same issue... so for now using `useFactory` as suggested by @pgrzywaczcic.

Any chance this would be solved?

**Comment by mickaeltr** [comment]
I gave a second though to this issue and it now makes sense to me why `useFactory` must be used for mocks.

This is an abstract what I did eventually:
```typescript
import { GetReferenceDataService } from "./get-reference-data.service";
jest.mock("./get-reference-data.service");

describe("MyComponent", () => {
  let component: MyComponent;
  let fixture: ComponentFixture<MyComponent>;
  let getReferenceData: GetReferenceDataService;

  configureTestSuite(() => {
    TestBed.configureTestingModule({
      declarations: […],
      imports: […],
      schemas: [CUSTOM_ELEMENTS_SCHEMA],
      providers: [{provide: GetReferenceDataService, useFactory: (): GetReferenceDataService => getReferenceData}]
    });
  });

  beforeEach(() => {
    const getReferenceData: GetReferenceDataService = new GetReferenceDataService(null);
    mocked(getReferenceData).perform.mockReturnValue({…});

    fixture = TestBed.createComponent(MyComponent);
    component = fixture.componentInstance;
    fixture.detectChanges();
  });

  …
```
