### ISSUE TITLE
something went wrong

### ISSUE THREAD

**Issue by JaroslavPrt** [topnotch48/ng-bullet-workspace#4]
have a lot of unit tests))) with few nested "describe" blocks each has own "beforeEach" function.

It works perfectly in standard way with configure testing module in "beforeEach".
Module imports "Core" and "Shared" modules, mocked component and provides seven mocked services.

- when i'm trying to use "configureTestSuite" 30% +/- of tests have fallen.
- when i'm running tests not in random order only few test have fallen

Did i something wrong or miss?!

Also in "global" beforeEach function i've tried to use createTestContext/createStableTestContext it didn't help to.

**upd**
and methods that called in `onInit` hook and expect `toHaveBeenCalledTimes(1)`, seems to be called for each test, so test module not resetting for each test ?

**Comment by JAspeling** [comment]
That's exactly what this package does - it doesn't recompile the components every time, saving time while running the tests..
