### ISSUE TITLE
ng-bullet does not work with apps in Ivy mode

### ISSUE THREAD

**Issue by sharikovvladislav** [topnotch48/ng-bullet-workspace#8]
Hi!

At the moment Angular (9.0.0-rc.3) has Ivy-renderer as opt-out feature, so you have to turn it off if you don't want it.

In our project we have about 2500~ unit tests. ~1000 of them depends on `ng-bullet` package.

The problem:
We redeclare different mock objects in our test suites in `beforeEach` (we use karma + jasmine for testing). When we run tests in Ivy, those re-defines do nothing (with `ng-bullet`).

I researched a bit and looks like there is problem in how you reset TestBed instance for the test suit.
I found that you do it through the `testBedApi._instantiated = false;` line in the `testing.ts`. It is working with ViewEngine. Ivy is a new renderer and Angular also has new TestBed for Ivy. Internals changed and there is no property `_instantiated` in the TestBed.

**Comment by sharikovvladislav** [comment]
I created the PR to fix this. #9

**Comment by sharikovvladislav** [comment]
This change fixed ~1000 units in our project.

**Comment by pkaufi** [comment]
I also stumbled upon this while upgrading our project to ivy. However, I decided to completely drop `ng-bullet`.
The article (https://blog.angular.io/version-9-of-angular-now-available-project-ivy-has-arrived-23c97b63cfa3) mentions

> Faster testing
> We have also revamped the implementation of TestBed in Ivy to make it more efficient.
> Previously, TestBed would recompile all components between the running of each test, regardless > of whether there were any changes made to components (for example, through overrides).
> In Ivy, TestBed doesn’t recompile components between tests unless a component has been > manually overridden, which allows it to avoid recompilation between the grand majority of tests.
> With this change, the framework’s core acceptance tests are about 40% faster. We would expect > users to see their own application test speeds to be around 40–50% faster.

I have to admit, that we used it only for one test that was running incredibly slow because of a lot of dependencies and `ng-bullet` really helped running it faster. It now runs within 28 seconds compared to the 20 seconds I had with `ng-bullet`. I'm ok with that slight increase of testing time, and I'm not sure how it is in your project @sharikovvladislav . However, it'd be very interesting to see the difference in your case, as you have a lot of tests depending on `ng-bullet`

**Comment by C0ZEN** [comment]
I really need this feature. @topnotch48 could you please accept ASAP the PR from @sharikovvladislav ?

**Comment by sharikovvladislav** [comment]
@C0ZEN we wait this too :(

Actually, did you try to fully remove ng-bullet (like @pkaufi mentioned)? In 9.0.0 with Ivy test should be faster out of the box.

**Comment by C0ZEN** [comment]
@sharikovvladislav yes, I could not wait for ng-bullet to be fixed.
I removed it and I do not plan to put it back if at some point a new release is made.

**Comment by sharikovvladislav** [comment]
@C0ZEN do you have any time stats?

Like:
- units with ng-bullet (with fix from this PR, you can fix it in your node_modules)
- units without ng-bullet at all

?

**Comment by C0ZEN** [comment]
@sharikovvladislav no, however I have more than 5k tests and it seems more or less identical between ng8 with ng-bullet and ng9 without it.
I could not tell for sure but in both cases karma took always less than 25s for running them all.

**Comment by bjsawyer** [comment]
While I loved ng-bullet for ng8, it seems like Angular baked in the optimizations with their release of ng9. I too have switched back to the standard CLI way of setting up tests and they're running as fast if not faster than they were for ng8 w/ ng-bullet. Good find @pkaufi 🥇

**Comment by C0ZEN** [comment]
Too bad that it took so long.
I finally figured out that even with Ivy, ng-bullet is still better to increase performances nevertheless I had to move one due to the error.
Refactoring once again my 8k tests to add back ng-bullet would be insane and covid is enough for that.

**Comment by karthik2294** [comment]
when will be the fixed ng-bullet get published in npm??

**Comment by sozakir** [comment]
+1 when it would be pulished to npm @topnotch48

**Comment by topnotch48** [comment]
Please excuse me, but it seems like I don't have time to invest into this
library anymore. This being said please let me provide you with an even
better alternative in my opinion - spectator
<https://github.com/ngneat/spectator>, backed by Netanel Basal. It should
provide you a similar technique to speed up your tests, plus many more
useful tools to improve testing of your application.
Excuse me once again for inconvenience.
